In [1]:
import pandas as pd
data={
    "Student_ID":[101,102,103,104,105,106,102,107],
    "Student":["Asha","Ravi","Priya","John","Anu","Kiran","Ravi","Meena"],
    "Department":["CSE","CSE","ECE","ECE","CSE","EEE","CSE","EEE"],
    "Attendance":[90,75,95,60,80,70,75,85],
    "Internal_Marks":[85,70,90,55,78,65,70,None],
    "Final_Marks":[88,72,92,50,80,68,72,82]
}

df=pd.DataFrame(data)
df.to_csv("Students.csv", index=False)
print("Students.csv created successfully!")

Students.csv created successfully!

In [2]:
df=pd.read_csv("Students.csv")
print("\nOriginal Dataset:\n")
df

Original Dataset:

   Student_ID Student Department  Attendance  Internal_Marks  Final_Marks
0         101    Asha        CSE          90            85.0           88
1         102    Ravi        CSE          75            70.0           72
2         103   Priya        ECE          95            90.0           92
3         104    John        ECE          60            55.0           50
4         105     Anu        CSE          80            78.0           80
5         106   Kiran        EEE          70            65.0           68
6         102    Ravi        CSE          75            70.0           72
7         107   Meena        EEE          85             NaN           82

In [3]:
print("\nFirst five records:\n")
df.head()

First five records:

   Student_ID Student Department  Attendance  Internal_Marks  Final_Marks
0         101    Asha        CSE          90            85.0           88
1         102    Ravi        CSE          75            70.0           72
2         103   Priya        ECE          95            90.0           92
3         104    John        ECE          60            55.0           50
4         105     Anu        CSE          80            78.0           80

In [4]:
print("\nLast five records:\n")
df.tail()

Last five records:

   Student_ID Student Department  Attendance  Internal_Marks  Final_Marks
3         104    John        ECE          60            55.0           50
4         105     Anu        CSE          80            78.0           80
5         106   Kiran        EEE          70            65.0           68
6         102    Ravi        CSE          75            70.0           72
7         107   Meena        EEE          85             NaN           82

In [5]:
print("\nDataset Shape:\n")
df.shape

Dataset Shape:

(8, 6)

In [6]:
print("\nCheck datatype:\n")
df.dtypes

Check datatype:

Student_ID          int64
Student               str
Department            str
Attendance          int64
Internal_Marks    float64
Final_Marks         int64
dtype: object

In [7]:
print("\nDiscription Statistics:\n")
df.describe()

Discription Statistics:

       Student_ID  Attendance  Internal_Marks  Final_Marks
count     8.00000    8.000000        7.000000     8.000000
mean    103.75000   78.750000       73.285714    75.500000
std       2.12132   11.259916       11.996031    13.212548
min     101.00000   60.000000       55.000000    50.000000
25%     102.00000   73.750000       67.500000    71.000000
50%     103.50000   77.500000       70.000000    76.000000
75%     105.25000   86.250000       81.500000    83.500000
max     107.00000   95.000000       90.000000    92.000000

In [8]:
print("\nMissing Values:\n")
print(df.isnull().sum())

Missing Values:

Student_ID        0
Student           0
Department        0
Attendance        0
Internal_Marks    1
Final_Marks       0
dtype: int64

In [9]:
print("\nNumbber of Duplicate Records:\n")
print(df.duplicated().sum())
df=df.drop_duplicates()

Numbber of Duplicate Records:

1

In [10]:
print("\nAverage Final Marks by Department:\n")
df.groupby("Department")["Final_Marks"].mean()

Average Final Marks by Department:

Department
CSE    80.0
ECE    71.0
EEE    75.0
Name: Final_Marks, dtype: float64

In [11]:
courses=pd.DataFrame({
    "Student_ID":[101,102,103,104,105,106,107],
    "Courese":["Python","Python","Java","Python","Java","Python","Java"]
})
merged_df=pd.merge(df,courses,on="Student_ID")
print("\nMerged Dataset:\n")
merged_df

Merged Dataset:

,Student_ID,Student,Department,Attendance,Internal_Marks,Final_Marks,Courese
0,101,Asha,CSE,90,85.0,88,Python
1,102,Ravi,CSE,75,70.0,72,Python
2,103,Priya,ECE,95,90.0,92,Java
3,104,John,ECE,60,55.0,50,Python
4,105,Anu,CSE,80,78.0,80,Java
5,106,Kiran,EEE,70,65.0,68,Python
6,107,Meena,EEE,85,NaN,82,Java